package net.minecraft.src.dqmcore;
import net.minecraft.src.*;

public class DqmAddName extends mod_Dqm
{

	public DqmAddName()
	{}
	public static void setName()
	{
		//新アイテム
		ModLoader.addName(Ginnoyubiwa, "Silver ring");
		ModLoader.addName(Inotinoyubiwa, "Rings of Life");
		ModLoader.addName(Ginnoyubiwa, "ja_JP", "ぎんのゆびわ");
		ModLoader.addName(Inotinoyubiwa, "ja_JP", "命のゆびわ");

		ModLoader.addName(Haganenoono, "Ono of steel");
		ModLoader.addName(Haounoono, "Ono of Overlord");
		ModLoader.addName(Oriharukonbou, "Oriharukon");
		ModLoader.addName(Konbou, "Club");
		ModLoader.addName(Haganenokon, "Club of steel");
		ModLoader.addName(Wohanma, "Warhammer");
		ModLoader.addName(Haganenoono, "ja_JP", "はがねのオノ");
		ModLoader.addName(Haounoono, "ja_JP", "はおうのオノ");
		ModLoader.addName(Oriharukonbou, "ja_JP", "オリハルこん");
		ModLoader.addName(Konbou, "ja_JP", "こんぼう");
		ModLoader.addName(Haganenokon, "ja_JP", "はがねのこん");
		ModLoader.addName(Wohanma, "ja_JP", "ウォーハンマー");

		ModLoader.addName(Akaisango, "Red coral");
		ModLoader.addName(Ayakasisou, "Ayakashi grass");
		ModLoader.addName(Budouekisu, "Grape extract");
		ModLoader.addName(Dokudokuhedoro, "Dokudoku sludge");
		ModLoader.addName(Dokuganokona, "Powder fang");
		ModLoader.addName(Gamanoabura, "Fat toad");
		ModLoader.addName(Hananomitu, "Flower nectar");
		ModLoader.addName(Hebinonukegara, "Husk of the snake");
		ModLoader.addName(Maryokunotuti, "Magic soil");
		ModLoader.addName(Meijikimeranohane, "Meijikimera feathers");
		ModLoader.addName(Nekozuna, "Sand cat");
		ModLoader.addName(Ryuunohizake, "Firewater of the Dragon");
		ModLoader.addName(Siroikaigara, "White seashell");
		ModLoader.addName(Tensinohane, "Wings of angel");
		ModLoader.addName(Tensinosoma, "Soma of angel wings");
		ModLoader.addName(Tetunokugi, "Of iron nails");
		ModLoader.addName(Toukonekisu, "Extract Fighting Spirit");
		ModLoader.addName(Tukemonoisi, "Stone pickles");
		ModLoader.addName(Tukinomegumi, "Grace of the month");
		ModLoader.addName(Umanofun, "Horse dung");
		ModLoader.addName(Usinofun, "Cow dung");
		ModLoader.addName(Yorunotobari, "Burr and the twist");
		ModLoader.addName(Kingdaiya, "King Diamond");
		ModLoader.addName(Genmaseki, "Gemma cough");
		ModLoader.addName(Furubitaring, "An old ring");
		ModLoader.addName(Akaisango, "ja_JP", "赤いサンゴ");
		ModLoader.addName(Ayakasisou, "ja_JP", "あやかし草");
		ModLoader.addName(Budouekisu, "ja_JP", "ぶどうエキス");
		ModLoader.addName(Dokudokuhedoro, "ja_JP", "どくどくヘドロ");
		ModLoader.addName(Dokuganokona, "ja_JP", "どくがの粉");
		ModLoader.addName(Gamanoabura, "ja_JP", "ガマのあぶら");
		ModLoader.addName(Hananomitu, "ja_JP", "花のみつ");
		ModLoader.addName(Hebinonukegara, "ja_JP", "ヘビのぬけがら");
		ModLoader.addName(Maryokunotuti, "ja_JP", "まりょくの土");
		ModLoader.addName(Meijikimeranohane, "ja_JP", "メイジキメラのはね");
		ModLoader.addName(Nekozuna, "ja_JP", "ネコ砂");
		ModLoader.addName(Ryuunohizake, "ja_JP", "竜の火酒");
		ModLoader.addName(Siroikaigara, "ja_JP", "白いかいがら");
		ModLoader.addName(Tensinohane, "ja_JP", "てんしのはね");
		ModLoader.addName(Tensinosoma, "ja_JP", "てんしのソーマ");
		ModLoader.addName(Tetunokugi, "ja_JP", "てつのクギ");
		ModLoader.addName(Toukonekisu, "ja_JP", "とうこんエキス");
		ModLoader.addName(Tukemonoisi, "ja_JP", "つけもの石");
		ModLoader.addName(Tukinomegumi, "ja_JP", "月のめぐみ");
		ModLoader.addName(Umanofun, "ja_JP", "うまのふん");
		ModLoader.addName(Usinofun, "ja_JP", "うしのふん");
		ModLoader.addName(Yorunotobari, "ja_JP", "よるのとばり");
		ModLoader.addName(Kingdaiya, "ja_JP", "キングダイヤ");
		ModLoader.addName(Genmaseki, "ja_JP", "げんませき");
		ModLoader.addName(Furubitaring, "ja_JP", "古びたリング");

		ModLoader.addName(Ayasiikobin, "Small pin suspicious");
		ModLoader.addName(Bekkou, "Tortoiseshell");
		ModLoader.addName(Doragonnonamida, "Tears of the Dragon");
		ModLoader.addName(Haganenoobane, "Steel tail feathers");
		ModLoader.addName(Hepaitosunohidane, "Flashpoint Hepaitosu");
		ModLoader.addName(Hyoutyounohane, "Ice bird feather");
		ModLoader.addName(Juryokunomoto, "Moto Juryoku");
		ModLoader.addName(Kiyomenomizu, "Ablution");
		ModLoader.addName(Kyodaihigetokage, "Higetokage huge");
		ModLoader.addName(Nebanebazeri, "Gooey jelly");
		ModLoader.addName(Nijiirononunokire, "Ground color of the cloth");
		ModLoader.addName(Risaikurusuton, "Stone Recycling");
		ModLoader.addName(Saezurinomitu, "Mitsu twitter");
		ModLoader.addName(Seinarusizuku, "Drops of holy");
		ModLoader.addName(Seisui, "Holy water");
		ModLoader.addName(Suraimuosyarebana, "Fashionable flower slime");
		ModLoader.addName(Uraminohouju, "Resentment towards the tree");
		ModLoader.addName(Ayasiikobin, "ja_JP", "あやしい小ピン");
		ModLoader.addName(Bekkou, "ja_JP", "べっこう");
		ModLoader.addName(Doragonnonamida, "ja_JP", "ドラゴンのなみだ");
		ModLoader.addName(Haganenoobane, "ja_JP", "はがねの尾羽");
		ModLoader.addName(Hepaitosunohidane, "ja_JP", "ヘパイトスのひだね");
		ModLoader.addName(Hyoutyounohane, "ja_JP", "氷鳥のはね");
		ModLoader.addName(Juryokunomoto, "ja_JP", "呪力のモト");
		ModLoader.addName(Kiyomenomizu, "ja_JP", "きよめの水");
		ModLoader.addName(Kyodaihigetokage, "ja_JP", "巨大ヒゲトカゲ");
		ModLoader.addName(Nebanebazeri, "ja_JP", "ねばねばゼリー");
		ModLoader.addName(Nijiirononunokire, "ja_JP", "にじいろの布きれ");
		ModLoader.addName(Risaikurusuton, "ja_JP", "リサイクルストーン");
		ModLoader.addName(Saezurinomitu, "ja_JP", "さえずりのみつ");
		ModLoader.addName(Seinarusizuku, "ja_JP", "せいなるのしずく");
		ModLoader.addName(Seisui, "ja_JP", "せいすい");
		ModLoader.addName(Suraimuosyarebana, "ja_JP", "スライムおしゃれ花");
		ModLoader.addName(Uraminohouju, "ja_JP", "うらみのほうじゅ");



		//ブロック
        ModLoader.addName(DqmBlockHako, "Wood Box");
        ModLoader.addName(DqmBlockHako, "ja_JP", "木箱");
        ModLoader.addName(DqmBlockGenkotu, "Daque fist");
        ModLoader.addName(DqmBlockGenkotu, "ja_JP", "げんこつダケ");

		//実アイテム
		ModLoader.addName(Yakusou, "Medicinal herb");
		ModLoader.addName(Yakusou, "ja_JP", "薬草");
		ModLoader.addName(Dokukesisou, "Antidote for poison herb");
		ModLoader.addName(Dokukesisou, "ja_JP", "毒消し草");
		ModLoader.addName(Tikaranotane, "Seed of power");
		ModLoader.addName(Tikaranotane, "ja_JP", "力の種");
		ModLoader.addName(Mamorinotane, "Seed of defense");
		ModLoader.addName(Mamorinotane, "ja_JP", "守りの種");
		ModLoader.addName(Subayasanotane, "Seed of quickness");
		ModLoader.addName(Subayasanotane, "ja_JP", "素早さの種");
		ModLoader.addName(Ougon, "Golden seed");
		ModLoader.addName(Ougon, "ja_JP", "黄金の実");
		ModLoader.addName(Honoonomi, "Fire seed");
		ModLoader.addName(Honoonomi, "ja_JP", "炎の実");
		ModLoader.addName(Iyasinomi, "Healing seed");
		ModLoader.addName(Iyasinomi, "ja_JP", "いやしの実");

		ModLoader.addName(Yakusou2, "Medicinal herb2");
		ModLoader.addName(Yakusou2, "ja_JP", "超薬草");
		ModLoader.addName(Dokukesisou2, "Antidote for poison herb2");
		ModLoader.addName(Dokukesisou2, "ja_JP", "超毒消し草");
		ModLoader.addName(Tikaranotane2, "Seed of power2");
		ModLoader.addName(Tikaranotane2, "ja_JP", "超力の種");
		ModLoader.addName(Mamorinotane2, "Seed of defense2");
		ModLoader.addName(Mamorinotane2, "ja_JP", "超守りの種");
		ModLoader.addName(Subayasanotane2, "Seed of quickness2");
		ModLoader.addName(Subayasanotane2, "ja_JP", "超素早さの種");
		ModLoader.addName(Ougon2, "Golden seed2");
		ModLoader.addName(Ougon2, "ja_JP", "超黄金の実");
		ModLoader.addName(Honoonomi2, "Fire seed2");
		ModLoader.addName(Honoonomi2, "ja_JP", "超炎の実");
		ModLoader.addName(Iyasinomi2, "Healing seed2");
		ModLoader.addName(Iyasinomi2, "ja_JP", "超いやしの実");

		ModLoader.addName(Yakusou3, "Medicinal herb3");
		ModLoader.addName(Yakusou3, "ja_JP", "極薬草");
		ModLoader.addName(Dokukesisou3, "Antidote for poison herb3");
		ModLoader.addName(Dokukesisou3, "ja_JP", "極毒消し草");
		ModLoader.addName(Tikaranotane3, "Seed of power3");
		ModLoader.addName(Tikaranotane3, "ja_JP", "極力の種");
		ModLoader.addName(Mamorinotane3, "Seed of defense3");
		ModLoader.addName(Mamorinotane3, "ja_JP", "極守りの種");
		ModLoader.addName(Subayasanotane3, "Seed of quickness3");
		ModLoader.addName(Subayasanotane3, "ja_JP", "極素早さの種");
		ModLoader.addName(Ougon3, "Golden seed3");
		ModLoader.addName(Ougon3, "ja_JP", "極黄金の実");
		ModLoader.addName(Honoonomi3, "Fire seed3");
		ModLoader.addName(Honoonomi3, "ja_JP", "極炎の実");
		ModLoader.addName(Iyasinomi3, "Healing seed3");
		ModLoader.addName(Iyasinomi3, "ja_JP", "極いやしの実");

		//種ブロック
		ModLoader.addName(YakusouSeed, "YakusouSeed(Block)");
		ModLoader.addName(YakusouSeed, "ja_JP", "薬草(ブロック)");
		ModLoader.addName(DokukesisouSeed, "DokukesisouSeed(Block)");
		ModLoader.addName(DokukesisouSeed, "ja_JP", "毒消し草(ブロック)");
		ModLoader.addName(TikaraSeed, "TikaraSeed(Block)");
		ModLoader.addName(TikaraSeed, "ja_JP", "力の種(ブロック)");
		ModLoader.addName(MamoriSeed, "MamoriSeed(Block)");
		ModLoader.addName(MamoriSeed, "ja_JP", "守りの種(ブロック)");
		ModLoader.addName(SubayasaSeed, "SubayasaSeed(Block)");
		ModLoader.addName(SubayasaSeed, "ja_JP", "素早さの種(ブロック)");
		ModLoader.addName(OugonSeed, "OugonSeed(Block)");
		ModLoader.addName(OugonSeed, "ja_JP", "黄金の種(ブロック)");
		ModLoader.addName(HonooSeed, "HonooSeed(Block)");
		ModLoader.addName(HonooSeed, "ja_JP", "炎の種(ブロック)");
		ModLoader.addName(IyasiSeed, "IyasiSeed(Block)");
		ModLoader.addName(IyasiSeed, "ja_JP", "いやしの種(ブロック)");

		ModLoader.addName(YakusouSeed2, "YakusouSeed2(Block)");
		ModLoader.addName(YakusouSeed2, "ja_JP", "超薬草(ブロック)");
		ModLoader.addName(DokukesisouSeed2, "DokukesisouSeed2(Block)");
		ModLoader.addName(DokukesisouSeed2, "ja_JP", "超毒消し草(ブロック)");
		ModLoader.addName(TikaraSeed2, "TikaraSeed2(Block)");
		ModLoader.addName(TikaraSeed2, "ja_JP", "超力の種(ブロック)");
		ModLoader.addName(MamoriSeed2, "MamoriSeed2(Block)");
		ModLoader.addName(MamoriSeed2, "ja_JP", "超守りの種(ブロック)");
		ModLoader.addName(SubayasaSeed2, "SubayasaSeed2(Block)");
		ModLoader.addName(SubayasaSeed2, "ja_JP", "超素早さの種(ブロック)");
		ModLoader.addName(OugonSeed2, "OugonSeed2(Block)");
		ModLoader.addName(OugonSeed2, "ja_JP", "超黄金の種(ブロック)");
		ModLoader.addName(HonooSeed2, "HonooSeed2(Block)");
		ModLoader.addName(HonooSeed2, "ja_JP", "超炎の種(ブロック)");
		ModLoader.addName(IyasiSeed2, "IyasiSeed2(Block)");
		ModLoader.addName(IyasiSeed2, "ja_JP", "超いやしの種(ブロック)");

		ModLoader.addName(YakusouSeed3, "YakusouSeed3(Block)");
		ModLoader.addName(YakusouSeed3, "ja_JP", "極薬草(ブロック)");
		ModLoader.addName(DokukesisouSeed3, "DokukesisouSeed3(Block)");
		ModLoader.addName(DokukesisouSeed3, "ja_JP", "極毒消し草(ブロック)");
		ModLoader.addName(TikaraSeed3, "TikaraSeed3(Block)");
		ModLoader.addName(TikaraSeed3, "ja_JP", "極力の種(ブロック)");
		ModLoader.addName(MamoriSeed3, "MamoriSeed3(Block)");
		ModLoader.addName(MamoriSeed3, "ja_JP", "極守りの種(ブロック)");
		ModLoader.addName(SubayasaSeed3, "SubayasaSeed3(Block)");
		ModLoader.addName(SubayasaSeed3, "ja_JP", "極素早さの種(ブロック)");
		ModLoader.addName(OugonSeed3, "OugonSeed3(Block)");
		ModLoader.addName(OugonSeed3, "ja_JP", "極黄金の種(ブロック)");
		ModLoader.addName(HonooSeed3, "HonooSeed3(Block)");
		ModLoader.addName(HonooSeed3, "ja_JP", "極炎の種(ブロック)");
		ModLoader.addName(IyasiSeed3, "IyasiSeed3(Block)");
		ModLoader.addName(IyasiSeed3, "ja_JP", "極いやしの種(ブロック)");


		//種アイテム
		ModLoader.addName(ItemYakusouSeed, "Herb(Seed)");
		ModLoader.addName(ItemYakusouSeed, "ja_JP", "薬草(種)");
		ModLoader.addName(ItemDokukesisouSeed, "Grass Antidote(Seed)");
		ModLoader.addName(ItemDokukesisouSeed, "ja_JP", "毒消し草(種)");
		ModLoader.addName(ItemTikaraSeed, "Motodane of force(Seed)");
		ModLoader.addName(ItemTikaraSeed, "ja_JP", "力の種(種)");
		ModLoader.addName(ItemMamoriSeed, "Motodane defensive(Seed)");
		ModLoader.addName(ItemMamoriSeed, "ja_JP", "守りの種(種)");
		ModLoader.addName(ItemSubayasaSeed, "Motodane of rapidity(Seed)");
		ModLoader.addName(ItemSubayasaSeed, "ja_JP", "素早さの種(種)");
		ModLoader.addName(ItemOugonSeed, "Golden seed(Seed)");
		ModLoader.addName(ItemOugonSeed, "ja_JP", "黄金の種(種)");
		ModLoader.addName(ItemHonooSeed, "Fire seed(Seed)");
		ModLoader.addName(ItemHonooSeed, "ja_JP", "炎の種(種)");
		ModLoader.addName(ItemIyasiSeed, "Healing seed(Seed)");
		ModLoader.addName(ItemIyasiSeed, "ja_JP", "いやしの種(種)");

		ModLoader.addName(ItemYakusouSeed2, "Herb2(Seed)");
		ModLoader.addName(ItemYakusouSeed2, "ja_JP", "超薬草(種)");
		ModLoader.addName(ItemDokukesisouSeed2, "Grass Antidote2(Seed)");
		ModLoader.addName(ItemDokukesisouSeed2, "ja_JP", "超毒消し草(種)");
		ModLoader.addName(ItemTikaraSeed2, "Motodane of force2(Seed)");
		ModLoader.addName(ItemTikaraSeed2, "ja_JP", "超力の種(種)");
		ModLoader.addName(ItemMamoriSeed2, "Motodane defensive2(Seed)");
		ModLoader.addName(ItemMamoriSeed2, "ja_JP", "超守りの種(種)");
		ModLoader.addName(ItemSubayasaSeed2, "Motodane of rapidity2(Seed)");
		ModLoader.addName(ItemSubayasaSeed2, "ja_JP", "超素早さの種(種)");
		ModLoader.addName(ItemOugonSeed2, "Golden seed2(Seed)");
		ModLoader.addName(ItemOugonSeed2, "ja_JP", "超黄金の種(種)");
		ModLoader.addName(ItemHonooSeed2, "Fire seed2(Seed)");
		ModLoader.addName(ItemHonooSeed2, "ja_JP", "超炎の種(種)");
		ModLoader.addName(ItemIyasiSeed2, "Healing seed2(Seed)");
		ModLoader.addName(ItemIyasiSeed2, "ja_JP", "超いやしの種(種)");

		ModLoader.addName(ItemYakusouSeed3, "Herb3(Seed)");
		ModLoader.addName(ItemYakusouSeed3, "ja_JP", "極薬草(種)");
		ModLoader.addName(ItemDokukesisouSeed3, "Grass Antidote3(Seed)");
		ModLoader.addName(ItemDokukesisouSeed3, "ja_JP", "極毒消し草(種)");
		ModLoader.addName(ItemTikaraSeed3, "Motodane of force3(Seed)");
		ModLoader.addName(ItemTikaraSeed3, "ja_JP", "極力の種(種)");
		ModLoader.addName(ItemMamoriSeed3, "Motodane defensive3(Seed)");
		ModLoader.addName(ItemMamoriSeed3, "ja_JP", "極守りの種(種)");
		ModLoader.addName(ItemSubayasaSeed3, "Motodane of rapidity3(Seed)");
		ModLoader.addName(ItemSubayasaSeed3, "ja_JP", "極素早さの種(種)");
		ModLoader.addName(ItemOugonSeed3, "Golden seed3(Seed)");
		ModLoader.addName(ItemOugonSeed3, "ja_JP", "極黄金の種(種)");
		ModLoader.addName(ItemHonooSeed3, "Fire seed3(Seed)");
		ModLoader.addName(ItemHonooSeed3, "ja_JP", "極炎の種(種)");
		ModLoader.addName(ItemIyasiSeed3, "Healing seed3(Seed)");
		ModLoader.addName(ItemIyasiSeed3, "ja_JP", "極いやしの種(種)");


		//鉱石
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 0), "ja_JP", "鉄鉱の原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 0), "Tekkouseki Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 1), "ja_JP", "溶岩の原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 1), "Yougansekinokakera Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 2), "ja_JP", "鏡の原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 2), "Kagaminoisi Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 3), "ja_JP", "ミスリルの原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 3), "Misriru Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 4), "ja_JP", "プラチナの原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 4), "Puratina Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 5), "ja_JP", "ヘビーメタルの原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 5), "Metal Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 6), "ja_JP", "ルビーの原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 6), "Rubi Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 7), "ja_JP", "月の原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 7), "Moon Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 8), "ja_JP", "光の原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 8), "Hikari Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 9), "ja_JP", "時の結晶の原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 9), "Toki Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 10), "ja_JP", "メダルの原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 10), "Medal Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 11), "ja_JP", "太陽の原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 11), "Taiyou Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 12), "ja_JP", "爆弾の原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 12), "Bakudan Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 13), "ja_JP", "星の砂");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 13), "Hosi Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 14), "ja_JP", "氷の塊");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 14), "Koori Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 15), "ja_JP", "磨き砂の塊");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 15), "Migaki Ore");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 15), "ja_JP", "命の石の原石");
        ModLoader.addName(new ItemStack(DqmBlockOre, 1, 15), "Inoti Ore");





		//アイテム名************************************************************************************************************************
		ModLoader.addName(Akumanotume, "Devil's claw");
		ModLoader.addName(Akumanotume, "ja_JP", "あくまのつめ");
		ModLoader.addName(Amatuyunoito, "ja_JP", "あまつゆの糸");
		ModLoader.addName(Amatuyunoito, "Yarn of Amatsuyu");
		ModLoader.addName(Atorasunokanaduti, "Atlas hammer");
		ModLoader.addName(Atorasunokanaduti, "ja_JP", "アトラスのかなづち");
		ModLoader.addName(Bakudanisi, "ja_JP", "爆弾石");
		ModLoader.addName(Bakudanisi, "Stone Bomb");
		ModLoader.addName(Bannouyaku, "ja_JP", "万能薬");
		ModLoader.addName(Bannouyaku, "Panacea");
		ModLoader.addName(Buruoubu, "Blue Orb");
		ModLoader.addName(Buruoubu, "ja_JP", "ブルーオーブ");
		ModLoader.addName(Debugsword, "Bow of Debug Sword");
		ModLoader.addName(Debugsword, "ja_JP", "デバッグソード");
		ModLoader.addName(Dokubari, "ja_JP", "どくばり");
		ModLoader.addName(Dokubari, "Stinger");
		ModLoader.addName(Doragonkira, "Dragon Killer");
		ModLoader.addName(Doragonkira, "ja_JP", "ドラゴンキラー");
		ModLoader.addName(Doragonmeiru, "Armor of Dragon");
		ModLoader.addName(Doragonmeiru, "ja_JP", "ドラゴンメイル");
		ModLoader.addName(Dragonrod, "Dragon rod");
		ModLoader.addName(Dragonrod, "ja_JP", "ドラゴンロッド");
		ModLoader.addName(Dragonwing, "Dragon Wing");
		ModLoader.addName(Dragonwing, "ja_JP", "ドラゴンウィング");
		ModLoader.addName(Ginganoturugi, "ja_JP", "銀河の剣");
		ModLoader.addName(Ginganoturugi,"Sword of Galaxy");
		ModLoader.addName(Goldburesuretto, "Gold Bracelet");
		ModLoader.addName(Goldburesuretto, "ja_JP", "ゴールドブレスレット");
		ModLoader.addName(Goldring, "Gold Ring");
		ModLoader.addName(Goldring, "ja_JP", "ゴールドリング");
		ModLoader.addName(Gouketunoudewa, "Heroes bangles");
		ModLoader.addName(Gouketunoudewa, "ja_JP", "ごうけつの腕輪");
		ModLoader.addName(Gureitoakusu, "Great Axe");
		ModLoader.addName(Gureitoakusu, "ja_JP", "グレートアックス");
		ModLoader.addName(Gurinoubu, "Green Orb");
		ModLoader.addName(Gurinoubu, "ja_JP", "グリーンオーブ");
		ModLoader.addName(Haganenokabuto, "Helmet of Hagane");
		ModLoader.addName(Haganenokabuto, "ja_JP", "鋼の兜");
		ModLoader.addName(Haganenokote, "Gauntlet of Hagane");
		ModLoader.addName(Haganenokote, "ja_JP", "鋼の小手");
		ModLoader.addName(Haganenokutu, "Boots of Hagane");
		ModLoader.addName(Haganenokutu, "ja_JP", "鋼のグリーブ");
		ModLoader.addName(Haganenoturugi, "ja_JP", "鋼の剣");
		ModLoader.addName(Haganenoturugi, "Sword of steel");
		ModLoader.addName(Haganenoyoroi, "Armor of Hagane");
		ModLoader.addName(Haganenoyoroi, "ja_JP", "鋼の鎧");
		ModLoader.addName(Hayabusanoturugi, "ja_JP", "はやぶさの剣");
		ModLoader.addName(Hayabusanoturugi, "Sword of Falcon ");
		ModLoader.addName(Hayatenoring, "ja_JP", "疾風のリング");
		ModLoader.addName(Hayatenoring, "Ring of Fast");
		ModLoader.addName(Heisinoken, "ja_JP", "兵士の剣");
		ModLoader.addName(Heisinoken, "Sword of the soldier");
		ModLoader.addName(Hikarinoisi, "ja_JP", "光の石");
		ModLoader.addName(Hikarinoisi, "Stone of Light");
		ModLoader.addName(Hikarinotue, "ja_JP", "ひかりの杖");
		ModLoader.addName(Hikarinotue, "Wand of light");
		ModLoader.addName(Hokoranokagi, "ja_JP", "ほこらのかぎ");
		ModLoader.addName(Hokoranokagi, "Shrine of key");
		ModLoader.addName(Honehone, "Bone Bone");
		ModLoader.addName(Honehone, "ja_JP", "ホネホネ");
		ModLoader.addName(Honoonoyoroi, "Armor of Flame");
		ModLoader.addName(Honoonoyoroi, "ja_JP", "炎の鎧");
		ModLoader.addName(Hosifuru, "ja_JP", "ほしふる腕輪");
		ModLoader.addName(Hosifuru, "Shooting Star Bracelet");
		ModLoader.addName(Hosinokakera, "ja_JP", "ほしのカケラ");
		ModLoader.addName(Hosinokakera, "Pieces of Star");
		ModLoader.addName(Ierooubu, "ja_JP", "イエローオーブ");
		ModLoader.addName(Ierooubu, "Yellow Orb");
		ModLoader.addName(Ikazutinotama, "Ball of thunder");
		ModLoader.addName(Ikazutinotama, "ja_JP", "いかずちの玉");
		ModLoader.addName(Ikazutinotue, "ja_JP", "いかずちのつえ");
		ModLoader.addName(Ikazutinotue, "Staff of Lightning");
		ModLoader.addName(Inferunosword, "ja_JP", "インフェルノソード");
		ModLoader.addName(Inferunosword, "Sword of Inferno");
		ModLoader.addName(Inferunoswordnoha, "Blade of Inferno");
		ModLoader.addName(Inferunoswordnoha, "ja_JP", "インフェルノソードの刃");
		ModLoader.addName(Inferunoswordnotuka, "Hilt of Inferno");
		ModLoader.addName(Inferunoswordnotuka, "ja_JP", "インフェルノソードの柄");
		ModLoader.addName(Inotinoisi, "ja_JP", "いのちの石");
		ModLoader.addName(Inotinoisi, "Stone of Life");
		ModLoader.addName(Jouyakusou, "ja_JP", "上やくそう");
		ModLoader.addName(Jouyakusou, "Over the medicinal plants");
		ModLoader.addName(Kagaminoisi, "ja_JP", "かがみの石");
		ModLoader.addName(Kagaminoisi, "Stone of Mirror");
		ModLoader.addName(Kawanobousi, "Cap of Leather");
		ModLoader.addName(Kawanobousi, "ja_JP", "皮のぼうし");
		ModLoader.addName(Kawanokote, "Gauntlet of Leather");
		ModLoader.addName(Kawanokote, "ja_JP", "皮のこて");
		ModLoader.addName(Kawanokutu, "ja_JP", "皮のくつ");
		ModLoader.addName(Kawanokutu, "Shoes of Leather");
		ModLoader.addName(Kawanoyoroi, "Armor of Leather");
		ModLoader.addName(Kawanoyoroi, "ja_JP", "皮の鎧");
		ModLoader.addName(Kazekirinohane, "ja_JP", "風切りの羽根");
		ModLoader.addName(Kazekirinohane, "Wings of The Wind");
		ModLoader.addName(Kazekirinoyumi, "Bow of The Wind");
		ModLoader.addName(Kazekirinoyumi, "ja_JP", "風切りの弓");
		ModLoader.addName(Kenjanoisi, "ja_JP", "けんじゃの石");
		ModLoader.addName(Kenjanoisi, "Philosopher's Stone");
		ModLoader.addName(Kenjanoseisui, "ja_JP", "賢者の聖水");
		ModLoader.addName(Kenjanoseisui, "Philosopher's of holy water");
		ModLoader.addName(Kimeranotubasa, "ja_JP", "キメラのつばさ");
		ModLoader.addName(Kimeranotubasa, "Wings of the chimeric");
		ModLoader.addName(Kinkai, "Gold Bullion");
		ModLoader.addName(Kinkai, "ja_JP", "金塊");
		ModLoader.addName(Kisekinoturugi, "ja_JP", "奇跡の剣");
		ModLoader.addName(Kisekinoturugi, "Sword of Miracles");
		ModLoader.addName(Koorinokessyou, "Ice Crystal");
		ModLoader.addName(Koorinokessyou, "ja_JP", "こおりの結晶");
		ModLoader.addName(Koorinoyaiba, "Blade of Ice");
		ModLoader.addName(Koorinoyaiba, "ja_JP", "氷の刃");
		ModLoader.addName(Koumorinohane, "Bat wings");
		ModLoader.addName(Koumorinohane, "ja_JP", "こうもりの羽根");
		ModLoader.addName(Kyodainakiba, "Giant Fang");
		ModLoader.addName(Kyodainakiba, "ja_JP", "巨大な牙");
		ModLoader.addName(Littlemedal, "ja_JP", "ちいさなメダル");
		ModLoader.addName(Littlemedal, "Little Medals");
		ModLoader.addName(Madarakumonoito, "ja_JP", "まだらクモ糸");
		ModLoader.addName(Madarakumonoito, "spider silk Madara");
		ModLoader.addName(Mahounokagi, "ja_JP", "まほうのかぎ");
		ModLoader.addName(Mahounokagi, "Magic of key");
		ModLoader.addName(Majinnokanaduti, "Hammer of Demon");
		ModLoader.addName(Majinnokanaduti, "ja_JP", "まじんのかなづち");
		ModLoader.addName(Majuunokawa, "ja_JP", "まじゅうの皮");
		ModLoader.addName(Majuunokawa, "Skin of the Beast");
		ModLoader.addName(Majuunotume, "Claw of beast");
		ModLoader.addName(Majuunotume, "ja_JP", "まじゅうのつめ");
		ModLoader.addName(Majuunotuno, "Corner of the Beast");
		ModLoader.addName(Majuunotuno, "ja_JP", "まじゅうの角");
		ModLoader.addName(Mamorinorubi, "ja_JP", "まもりのルビー");
		ModLoader.addName(Mamorinorubi, "Ruby defensive");
		ModLoader.addName(Metaloubu, "ja_JP", "メタルオーブ");
		ModLoader.addName(Metaloubu, "Metal Orb");
		ModLoader.addName(Metaru, "ja_JP", "ヘビーメタル");
		ModLoader.addName(Metaru, "Metal");
		ModLoader.addName(Metarukingnoha, "Blade of Metal");
		ModLoader.addName(Metarukingnoha, "ja_JP", "メタルキングの刃");
		ModLoader.addName(Metarukingnokabuto, "Helmet of Metal King");
		ModLoader.addName(Metarukingnokabuto, "ja_JP", "メタルキングの兜");
		ModLoader.addName(Metarukingnokote, "Gauntlet of Metal King");
		ModLoader.addName(Metarukingnokote, "ja_JP", "メタルキングの小手");
		ModLoader.addName(Metarukingnokutu, "Boots of Metal King");
		ModLoader.addName(Metarukingnokutu, "ja_JP", "メタルキングブーツ");
		ModLoader.addName(Metarukingnotuka, "Hilt of Metal");
		ModLoader.addName(Metarukingnotuka, "ja_JP", "メタルキングの柄");
		ModLoader.addName(Metarukingnoturugi, "ja_JP", "メタルキングの剣");
		ModLoader.addName(Metarukingnoturugi, "Sword of King Metal");
		ModLoader.addName(Metarukingnoyoroi, "Armor of Metal King");
		ModLoader.addName(Metarukingnoyoroi, "ja_JP", "メタルキングの鎧");
		ModLoader.addName(Midorinokoke, "ja_JP", "みどりコケ");
		ModLoader.addName(Midorinokoke, "Moss green");
		ModLoader.addName(Migakizuna, "ja_JP", "磨き砂");
		ModLoader.addName(Migakizuna, "Polishing Sand");
		ModLoader.addName(Mirayoroi, "Armor of Mirror");
		ModLoader.addName(Mirayoroi, "ja_JP", "ミラーアーマー");
		ModLoader.addName(Misriru, "ja_JP", "ミスリル");
		ModLoader.addName(Misriru, "Mithril");
		ModLoader.addName(Moon, "Diamond of the moon");
		ModLoader.addName(Moon, "ja_JP", "月のダイヤ");
		ModLoader.addName(MysteryEgg, "ja_JP", "謎の卵");
		ModLoader.addName(MysteryEgg, "Mystery Egg");
		ModLoader.addName(Oninokanabou, "ja_JP", "おにのかなぼう");
		ModLoader.addName(Oninokanabou, "Kanabo of ogre");
		ModLoader.addName(Ookanaduti, "Big hammer");
		ModLoader.addName(Ookanaduti, "ja_JP", "おおかなづち");
		ModLoader.addName(Oriharukon, "ja_JP", "オリハルコン");
		ModLoader.addName(Oriharukon, "Orichalcum");
		ModLoader.addName(Oujanoturugi, "ja_JP", "王者のつるぎ");
		ModLoader.addName(Oujanoturugi, "Sword of King");
		ModLoader.addName(Paapuruoubu, "ja_JP", "パープルオーブ");
		ModLoader.addName(Paapuruoubu, "パープルオーブ");
		ModLoader.addName(Papasunokatami, "ja_JP", "パパスの形見");
		ModLoader.addName(Papasunokatami, "Papas keepsake");
		ModLoader.addName(Papasunoturugi, "ja_JP", "パパスのつるぎ");
		ModLoader.addName(Papasunoturugi, "Sword of Papasu");
		ModLoader.addName(Papasunoturuginew, "ja_JP", "パパスのつるぎ改");
		ModLoader.addName(Papasunoturuginew, "Sword of Papasu New");
		ModLoader.addName(Puratina, "ja_JP", "プラチナ");
		ModLoader.addName(Puratina, "Platinum");
		ModLoader.addName(Rakkipendanto, "ja_JP", "ラッキーペンダント");
		ModLoader.addName(Rakkipendanto, "Lucky pendant");
		ModLoader.addName(Ramia, "ja_JP", "霊鳥の魂");
		ModLoader.addName(Ramia, "Soul of the sacred bird");
		ModLoader.addName(Redoubu, "ja_JP", "レッドオーブ");
		ModLoader.addName(Redoubu, "Red of Orb");
		ModLoader.addName(Rengokunohane, "Feathers purgatory");
		ModLoader.addName(Rengokunohane, "ja_JP", "れんごくの羽根");
		ModLoader.addName(Rotonoha, "Blade of Roto");
		ModLoader.addName(Rotonoha, "ja_JP", "ロトの刃");
		ModLoader.addName(Rotonokabuto, "Helmet of Roto");
		ModLoader.addName(Rotonokabuto, "ja_JP", "ロトの兜");
		ModLoader.addName(Rotonokote, "Gauntlet of Roto");
		ModLoader.addName(Rotonokote, "ja_JP", "ロトの小手");
		ModLoader.addName(Rotonokutu, "Boots of Roto");
		ModLoader.addName(Rotonokutu, "ja_JP", "ロトの靴");
		ModLoader.addName(Rotonotate, "ja_JP", "ロトの盾");
		ModLoader.addName(Rotonotate, "Shield of Roto");
		ModLoader.addName(Rotonotuka, "Hilt of Roto");
		ModLoader.addName(Rotonotuka, "ja_JP", "ロトの柄");
		ModLoader.addName(Rotonoturugi, "ja_JP", "ロトの剣");
		ModLoader.addName(Rotonoturugi, "Sword of Roto");
		ModLoader.addName(Rotonoyoroi, "Armor of Roto");
		ModLoader.addName(Rotonoyoroi, "ja_JP", "ロトの鎧");
		ModLoader.addName(Rubinogenseki, "ja_JP", "ルビーの原石");
		ModLoader.addName(Rubinogenseki, "Ruby Ore");
		ModLoader.addName(Ryuunonamida, "ja_JP", "竜のなみだ");
		ModLoader.addName(Ryuunonamida, "Tears of the Dragon");
		ModLoader.addName(Sabakinotue, "ja_JP", "さばきのつえ");
		ModLoader.addName(Sabakinotue, "Wand of justice");
		ModLoader.addName(Sabitakabuto, "Helmet of Old");
		ModLoader.addName(Sabitakabuto, "ja_JP", "錆びたロトの兜");
		ModLoader.addName(Sabitakote, "Gauntlet of Old");
		ModLoader.addName(Sabitakote, "ja_JP", "錆びたロトの小手");
		ModLoader.addName(Sabitakutu, "Boots of Old");
		ModLoader.addName(Sabitakutu, "ja_JP", "錆びたロトの靴");
		ModLoader.addName(Sabitatate, "ja_JP", "錆びたロトの盾");
		ModLoader.addName(Sabitatate, "Shield of Old");
		ModLoader.addName(Sabitayoroi, "Armor of Old");
		ModLoader.addName(Sabitayoroi, "ja_JP", "錆びたロトの鎧");
		ModLoader.addName(Saigonokagi, "ja_JP", "さいごのかぎ");
		ModLoader.addName(Saigonokagi, "Last of key");
		ModLoader.addName(Sefiramunoyumi, "Bow Sefiramu");
		ModLoader.addName(Sefiramunoyumi, "ja_JP", "セフィラムの弓");
		ModLoader.addName(Seijanohai, "Ash of the Saints");
		ModLoader.addName(Seijanohai, "ja_JP", "聖者の灰");
		ModLoader.addName(Seinarunaifu, "Holy knife");
		ModLoader.addName(Seinarunaifu, "ja_JP", "せいなるナイフ");
		ModLoader.addName(Seireiseki, "Elemental Stone");
		ModLoader.addName(Seireiseki, "ja_JP", "精霊石");
		ModLoader.addName(Sekaijunoha, "ja_JP", "せかいじゅの葉");
		ModLoader.addName(Sekaijunoha, "Leaves of the World Tree");
		ModLoader.addName(Sinkanohiseki, "ja_JP", "進化の秘石");
		ModLoader.addName(Sinkanohiseki, "Secret stone of evolution");
		ModLoader.addName(Sinpinoyoroi, "Armor of Mystery");
		ModLoader.addName(Sinpinoyoroi, "ja_JP", "神秘の鎧");
		ModLoader.addName(Suraimuhead, "ja_JP", "スライムヘッド");
		ModLoader.addName(Suraimuhead, "Slime Head");
		ModLoader.addName(Suraimunofuku, "ja_JP", "スライムのふく");
		ModLoader.addName(Suraimunofuku, "Slime Clothes");
		ModLoader.addName(Suraimunokanmuri, "Crown of slime");
		ModLoader.addName(Suraimunokanmuri, "ja_JP", "スライムの冠");
		ModLoader.addName(Suraimuzeri, "ja_JP", "スライムゼリー");
		ModLoader.addName(Suraimuzeri, "Slime jelly");
		ModLoader.addName(Taiyounoisi, "ja_JP", "たいようの石");
		ModLoader.addName(Taiyounoisi, "Stone of Sun");
		ModLoader.addName(Tekkouseki, "ja_JP", "鉄鋼石");
		ModLoader.addName(Tekkouseki, "Steel stone");
		ModLoader.addName(Tikaranorubi, "ja_JP", "ちからのルビー");
		ModLoader.addName(Tikaranorubi, "Ruby of force");
		ModLoader.addName(Togetogenokiba, "Fang spine");
		ModLoader.addName(Togetogenokiba, "ja_JP", "トゲトゲの牙");
		ModLoader.addName(Tokinosuisyou, "ja_JP", "時の水晶");
		ModLoader.addName(Tokinosuisyou, "Time of crystal");
		ModLoader.addName(Tokuyakusou, "ja_JP", "特やくそう");
		ModLoader.addName(Tokuyakusou, "Over the Special medicinal plants");
		ModLoader.addName(Toraidento, "ja_JP", "トライデント");
		ModLoader.addName(Toraidento, "Trident");
		ModLoader.addName(Touzokunokagi, "ja_JP", "とうぞくのかぎ");
		ModLoader.addName(Touzokunokagi, "Thief of key");
		ModLoader.addName(Tyounohane, "Butterfly wings");
		ModLoader.addName(Tyounohane, "ja_JP", "ちょうの羽");
		ModLoader.addName(Uminarinotue, "ja_JP", "海鳴りの杖");
		ModLoader.addName(Uminarinotue, "The sea noise wand");
		ModLoader.addName(Urokonoyoroi, "Armor of Scale");
		ModLoader.addName(Urokonoyoroi, "ja_JP", "うろこの鎧");
		ModLoader.addName(Uruwasikinoko, "Beauty or let mushroom");
		ModLoader.addName(Uruwasikinoko, "ja_JP", "うるわしキノコ");
		ModLoader.addName(Usaginosippo, "ja_JP", "うさぎのしっぽ");
		ModLoader.addName(Usaginosippo, "Tail of the rabbit");
		ModLoader.addName(Yaibanobumeran, "Boomerang blade");
		ModLoader.addName(Yaibanobumeran, "ja_JP", "やいばのブーメラン");
		ModLoader.addName(Yaibanoyoroi, "Armor of the Blade");
		ModLoader.addName(Yaibanoyoroi, "ja_JP", "刃の鎧");
		ModLoader.addName(Yawarakauru, "ja_JP", "やわらかウール");
		ModLoader.addName(Yawarakauru, "Soft wool");
		ModLoader.addName(Yogoretahoutai, "Dirty bandage");
		ModLoader.addName(Yogoretahoutai, "ja_JP", "よごれた包帯");
		ModLoader.addName(Yougansekinokakera, "Fragments of lava stone");
		ModLoader.addName(Yougansekinokakera, "ja_JP", "溶岩石のかけら");
		ModLoader.addName(Yuuwakunoyumi, "Bow of temptation");
		ModLoader.addName(Yuuwakunoyumi, "ja_JP", "ゆうわくの弓");



		//モンスター名（英）************************************************************************************************************************************************************
		ModLoader.addLocalization("entity.Arumiraji.name", "Large aluminum");
		ModLoader.addLocalization("entity.Atorasu.name", "Atlas");
		ModLoader.addLocalization("entity.Ayasiikage.name", "Suspicious shadow");
		ModLoader.addLocalization("entity.Bakudaniwa.name", "Bomb rock");
		ModLoader.addLocalization("entity.Behoimisuraimu.name", "Slime Behoimi");
		ModLoader.addLocalization("entity.Behoimusuraimu.name", "Behoimusuraimu");
		ModLoader.addLocalization("entity.BigCrow.name", "Oh glass");
		ModLoader.addLocalization("entity.Bubsura.name", "Bubble Slime");
		ModLoader.addLocalization("entity.Buraddihando.name", "Bloody Hand");
		ModLoader.addLocalization("entity.Dasudragon.name", "Dragon dozen");
		ModLoader.addLocalization("entity.Desufuratta.name", "Death flutter");
		ModLoader.addLocalization("entity.Doraki.name", "Doraki");
		ModLoader.addLocalization("entity.Dorakima.name", "Dorakima");
		ModLoader.addLocalization("entity.Dqmdragon.name", "Dragon");
		ModLoader.addLocalization("entity.Esterk.name", "Esutaku");
		ModLoader.addLocalization("entity.Furosutogizumo.name", "Frost Gizmos");
		ModLoader.addLocalization("entity.Gaikotukensi.name", "Manifesting skeleton");
		ModLoader.addLocalization("entity.Gamegon.name", "Gamegon");
		ModLoader.addLocalization("entity.Gamegonload.name", "Gamegonrodo");
		ModLoader.addLocalization("entity.Gamegonrejendo.name", "GamegonLegend");
		ModLoader.addLocalization("entity.Ghost.name", "Ghost");
		ModLoader.addLocalization("entity.Gigantesu.name", "Gigantes");
		ModLoader.addLocalization("entity.Gizumo.name", "Gizmo");
		ModLoader.addLocalization("entity.Goldman.name", "Goldman");
		ModLoader.addLocalization("entity.Goremu.name", "Golem");
		ModLoader.addLocalization("entity.Gorudensuraimu.name", "Golden Slime");
		ModLoader.addLocalization("entity.Gorudentotemu.name", "Golden Totem");
		ModLoader.addLocalization("entity.Hagumeta.name", "Missing Metal");
		ModLoader.addLocalization("entity.Herughost.name", "Hell Ghost");
		ModLoader.addLocalization("entity.Hiitogizumo.name", "Hitogizumo");
		ModLoader.addLocalization("entity.Hitokuibako.name", "Nonspecific box");
		ModLoader.addLocalization("entity.Hoimisura.name", "Hoimi slime");
		ModLoader.addLocalization("entity.Horoghost.name", "Holo-ghost");
		ModLoader.addLocalization("entity.Ikkakuusagi.name", "Rabbit corner");
		ModLoader.addLocalization("entity.Kagenokisi.name", "Knight of Shadows");
		ModLoader.addLocalization("entity.Kimera.name", "Chimera");
		ModLoader.addLocalization("entity.Kingsura.name", "King Slime");
		ModLoader.addLocalization("entity.Kiramasin.name", "Kiramashin");
		ModLoader.addLocalization("entity.Kirapan.name", "Kirapansa");
		ModLoader.addLocalization("entity.Kirikabuobake.name", "Ghost Stump");
		ModLoader.addLocalization("entity.Kisudragon.name", "Keith Dragon");
		ModLoader.addLocalization("entity.Kuinsuraimu.name", "Queen Slime");
		ModLoader.addLocalization("entity.Madohando.name", "Madohando");
		ModLoader.addLocalization("entity.Maounokage.name", "Shadow of the devil");
		ModLoader.addLocalization("entity.Marinsuraimu.name", "Marin slime");
		ModLoader.addLocalization("entity.Megazarurokku.name", "Megazarurokku");
		ModLoader.addLocalization("entity.Meijikimera.name", "Meijikimera");
		ModLoader.addLocalization("entity.Meragosuto.name", "Ghost camera");
		ModLoader.addLocalization("entity.Metaking.name", "Metal King");
		ModLoader.addLocalization("entity.Metaruburazazu.name", "Metal Brothers");
		ModLoader.addLocalization("entity.Metaruhanta.name", "Metal Hunter (bow)");
		ModLoader.addLocalization("entity.Metaruhantaken.name", "Metal Hunter (sword)");
		ModLoader.addLocalization("entity.Metaruraida.name", "Metal Rider");
		ModLoader.addLocalization("entity.Metasura.name", "Metal Slime");
		ModLoader.addLocalization("entity.Metoroghost.name", "Metro ghost");
		ModLoader.addLocalization("entity.Mimikku.name", "Mimic");
		ModLoader.addLocalization("entity.Pandorabox.name", "Pandora's box");
		ModLoader.addLocalization("entity.Puratinaking.name", "Platinum King");
		ModLoader.addLocalization("entity.Riripat.name", "Lilliput");
		ModLoader.addLocalization("entity.Samayoutamasii.name", "Wandering Spirit");
		ModLoader.addLocalization("entity.Sibirekurage.name", "Numbness jellyfish");
		ModLoader.addLocalization("entity.Siryounokisi.name", "Knights of the material");
		ModLoader.addLocalization("entity.Starkimera.name", "Star chimera");
		ModLoader.addLocalization("entity.Stonman.name", "Stoneman");
		ModLoader.addLocalization("entity.Sumairurokku.name", "Smile Rock");
		ModLoader.addLocalization("entity.Sura.name", "Slime");
		ModLoader.addLocalization("entity.Suraimubehomazun.name", "Dung Behoma slime");
		ModLoader.addLocalization("entity.Suraimubesu.name", "Beth slime");
		ModLoader.addLocalization("entity.Suraimumadyura.name", "Slime Made~yura");
		ModLoader.addLocalization("entity.Suraimunaito.name", "Slime Knight");
		ModLoader.addLocalization("entity.Suraimutawa.name", "Slime Tower");
		ModLoader.addLocalization("entity.Suraimutumuri.name", "Shut slime");
		ModLoader.addLocalization("entity.Syado.name", "Shadow");
		ModLoader.addLocalization("entity.Tahodoraki.name", "Tahodoraki");
		ModLoader.addLocalization("entity.Waraibukuro.name", "Laughter bag");
		ModLoader.addLocalization("entity.Zinmentyo.name", "Butterfly Face");
		ModLoader.addLocalization("entity.Zoma.name", "Zoma");
		ModLoader.addLocalization("entity.Batorurex.name", "Rex Battle");
		ModLoader.addLocalization("entity.DarkRamia.name", "Dark Ramia");


		//ペット
		ModLoader.addLocalization("entity.PetBakudaniwa.name", "[Pets]Bomb rocks ");
		ModLoader.addLocalization("entity.PetDorakima.name", "[Pets] Dorakima");
		ModLoader.addLocalization("entity.PetDqmdragon.name", "[Pets] Dragon");
		ModLoader.addLocalization("entity.PetGaikotukensi.name", "[Pets]Manifesting skeleton ");
		ModLoader.addLocalization("entity.PetGhost.name", "[Pets] ghost");
		ModLoader.addLocalization("entity.PetGigantesu.name", "[Pets] Gigantes");
		ModLoader.addLocalization("entity.PetGoremu.name", "[Pet] Golem");
		ModLoader.addLocalization("entity.PetHagumeta.name", "[Pets]Metal stray");
		ModLoader.addLocalization("entity.PetHitokuibako.name", "[Pets]Nonspecific box");
		ModLoader.addLocalization("entity.PetIkkakuusagi.name", "[Pets]Corner rabbit ");
		ModLoader.addLocalization("entity.PetKimera.name", "[Pets] chimera");
		ModLoader.addLocalization("entity.PetKingsura.name", "[Pets] King Slime");
		ModLoader.addLocalization("entity.PetKiramasin.name", "[Pets] Kiramashin");
		ModLoader.addLocalization("entity.PetKirapan.name", "[Pets] Kirapansa");
		ModLoader.addLocalization("entity.PetKirikabuobake.name", "[Pets]Ghost stump ");
		ModLoader.addLocalization("entity.PetKuinsuraimu.name", "[Pets] Queen Slime");
		ModLoader.addLocalization("entity.PetLittleEsterk.name", "[Pets] Little Esutaku");
		ModLoader.addLocalization("entity.PetMetoroghost.name", "[Pets] Metro ghost");
		ModLoader.addLocalization("entity.PetSura.name", "[Pets] slime");
		ModLoader.addLocalization("entity.PetSuraimunaito.name", "[Pets] Slime Knight");
		ModLoader.addLocalization("entity.PetSuraimutawa.name", "[Pets] Slime Tower");
		ModLoader.addLocalization("entity.PetSyado.name", "[Pets] Shadow");
		//モンスター名（日）************************************************************************************************************************************************************
		ModLoader.addLocalization("entity.Arumiraji.name", "ja_JP", "アルミラージ");
		ModLoader.addLocalization("entity.Atorasu.name", "ja_JP", "アトラス");
		ModLoader.addLocalization("entity.Ayasiikage.name", "ja_JP", "あやしいかげ");
		ModLoader.addLocalization("entity.Bakudaniwa.name", "ja_JP", "ばくだんいわ");
		ModLoader.addLocalization("entity.Behoimisuraimu.name", "ja_JP", "ベホイミスライム");
		ModLoader.addLocalization("entity.Behoimusuraimu.name", "ja_JP", "ベホイムスライム");
		ModLoader.addLocalization("entity.BigCrow.name", "ja_JP", "おおガラス");
		ModLoader.addLocalization("entity.Bubsura.name", "ja_JP", "バブルスライム");
		ModLoader.addLocalization("entity.Buraddihando.name", "ja_JP", "ブラッディハンド");
		ModLoader.addLocalization("entity.Dasudragon.name", "ja_JP", "ダースドラゴン");
		ModLoader.addLocalization("entity.Desufuratta.name", "ja_JP", "デスフラッター");
		ModLoader.addLocalization("entity.Doraki.name", "ja_JP", "ドラキー");
		ModLoader.addLocalization("entity.Dorakima.name", "ja_JP", "ドラキーマ");
		ModLoader.addLocalization("entity.Dqmdragon.name", "ja_JP", "ドラゴン");
		ModLoader.addLocalization("entity.Esterk.name", "ja_JP", "エスターク");
		ModLoader.addLocalization("entity.Furosutogizumo.name", "ja_JP", "フロストギズモ");
		ModLoader.addLocalization("entity.Gaikotukensi.name", "ja_JP", "がいこつけんし");
		ModLoader.addLocalization("entity.Gamegon.name", "ja_JP", "ガメゴン");
		ModLoader.addLocalization("entity.Gamegonload.name", "ja_JP", "ガメゴンロード");
		ModLoader.addLocalization("entity.Gamegonrejendo.name", "ja_JP", "ガメゴンレジェンド");
		ModLoader.addLocalization("entity.Ghost.name", "ja_JP", "ゴースト");
		ModLoader.addLocalization("entity.Gigantesu.name", "ja_JP", "ギガンテス");
		ModLoader.addLocalization("entity.Gizumo.name", "ja_JP", "ギズモ");
		ModLoader.addLocalization("entity.Goldman.name", "ja_JP", "ゴールドマン");
		ModLoader.addLocalization("entity.Goremu.name", "ja_JP", "ゴーレム");
		ModLoader.addLocalization("entity.Gorudensuraimu.name", "ja_JP", "ゴールデンスライム");
		ModLoader.addLocalization("entity.Gorudentotemu.name", "ja_JP", "ゴールデントーテム");
		ModLoader.addLocalization("entity.Hagumeta.name", "ja_JP", "はぐれメタル");
		ModLoader.addLocalization("entity.Herughost.name", "ja_JP", "ヘルゴースト");
		ModLoader.addLocalization("entity.Hiitogizumo.name", "ja_JP", "ヒートギズモ");
		ModLoader.addLocalization("entity.Hitokuibako.name", "ja_JP", "ひとくいばこ");
		ModLoader.addLocalization("entity.Hoimisura.name", "ja_JP", "ホイミスライム");
		ModLoader.addLocalization("entity.Horoghost.name", "ja_JP", "ホロゴースト");
		ModLoader.addLocalization("entity.Ikkakuusagi.name", "ja_JP", "いっかくうさぎ");
		ModLoader.addLocalization("entity.Kagenokisi.name", "ja_JP", "かげのきし");
		ModLoader.addLocalization("entity.Kimera.name", "ja_JP", "キメラ");
		ModLoader.addLocalization("entity.Kingsura.name", "ja_JP", "キングスライム");
		ModLoader.addLocalization("entity.Kiramasin.name", "ja_JP", "キラーマシン");
		ModLoader.addLocalization("entity.Kirapan.name", "ja_JP", "キラーパンサー");
		ModLoader.addLocalization("entity.Kirikabuobake.name", "ja_JP", "きりかぶおばけ");
		ModLoader.addLocalization("entity.Kisudragon.name", "ja_JP", "キースドラゴン");
		ModLoader.addLocalization("entity.Kuinsuraimu.name", "ja_JP", "クイーンスライム");
		ModLoader.addLocalization("entity.Madohando.name", "ja_JP", "マドハンド");
		ModLoader.addLocalization("entity.Maounokage.name", "ja_JP", "まおうのかげ");
		ModLoader.addLocalization("entity.Marinsuraimu.name", "ja_JP", "マリンスライム");
		ModLoader.addLocalization("entity.Megazarurokku.name", "ja_JP", "メガザルロック");
		ModLoader.addLocalization("entity.Meijikimera.name", "ja_JP", "メイジキメラ");
		ModLoader.addLocalization("entity.Meragosuto.name", "ja_JP", "メラゴースト");
		ModLoader.addLocalization("entity.Metaking.name", "ja_JP", "メタルキング");
		ModLoader.addLocalization("entity.Metaruburazazu.name", "ja_JP", "メタルブラザーズ");
		ModLoader.addLocalization("entity.Metaruhanta.name", "ja_JP", "メタルハンター（弓）");
		ModLoader.addLocalization("entity.Metaruhantaken.name", "ja_JP", "メタルハンター（剣）");
		ModLoader.addLocalization("entity.Metaruraida.name", "ja_JP", "メタルライダー");
		ModLoader.addLocalization("entity.Metasura.name", "ja_JP", "メタルスライム");
		ModLoader.addLocalization("entity.Metoroghost.name", "ja_JP", "メトロゴースト");
		ModLoader.addLocalization("entity.Mimikku.name", "ja_JP", "ミミック");
		ModLoader.addLocalization("entity.Pandorabox.name", "ja_JP", "パンドラボックス");
		ModLoader.addLocalization("entity.Puratinaking.name", "ja_JP", "プラチナキング");
		ModLoader.addLocalization("entity.Riripat.name", "ja_JP", "リリパット");
		ModLoader.addLocalization("entity.Samayoutamasii.name", "ja_JP", "さまようたましい");
		ModLoader.addLocalization("entity.Sibirekurage.name", "ja_JP", "しびれくらげ");
		ModLoader.addLocalization("entity.Siryounokisi.name", "ja_JP", "しりょうのきし");
		ModLoader.addLocalization("entity.Starkimera.name", "ja_JP", "スターキメラ");
		ModLoader.addLocalization("entity.Stonman.name", "ja_JP", "ストーンマン");
		ModLoader.addLocalization("entity.Sumairurokku.name", "ja_JP", "スマイルロック");
		ModLoader.addLocalization("entity.Sura.name", "ja_JP", "スライム");
		ModLoader.addLocalization("entity.Suraimubehomazun.name", "ja_JP", "スライムベホマズン");
		ModLoader.addLocalization("entity.Suraimubesu.name", "ja_JP", "スライムベス");
		ModLoader.addLocalization("entity.Suraimumadyura.name", "ja_JP", "スライムマデュラ");
		ModLoader.addLocalization("entity.Suraimunaito.name", "ja_JP", "スライムナイト");
		ModLoader.addLocalization("entity.Suraimutawa.name", "ja_JP", "スライムタワー");
		ModLoader.addLocalization("entity.Suraimutumuri.name", "ja_JP", "スライムつむり");
		ModLoader.addLocalization("entity.Syado.name", "ja_JP", "シャドー");
		ModLoader.addLocalization("entity.Tahodoraki.name", "ja_JP", "タホドラキー");
		ModLoader.addLocalization("entity.Waraibukuro.name", "ja_JP", "わらいぶくろ");
		ModLoader.addLocalization("entity.Zinmentyo.name", "ja_JP", "じんめんちょう");
		ModLoader.addLocalization("entity.Zoma.name", "ja_JP", "ゾーマ");
		ModLoader.addLocalization("entity.Batorurex.name", "ja_JP", "バトルレックス");
		ModLoader.addLocalization("entity.DarkRamia.name", "ja_JP", "ダークラーミア");

		//ペット
		ModLoader.addLocalization("entity.PetBakudaniwa.name", "ja_JP", "[ペット]ばくだんいわ");
		ModLoader.addLocalization("entity.PetDorakima.name", "ja_JP", "[ペット]ドラキーマ");
		ModLoader.addLocalization("entity.PetDqmdragon.name", "ja_JP", "[ペット]ドラゴン");
		ModLoader.addLocalization("entity.PetGaikotukensi.name", "ja_JP", "[ペット]がいこつけんし");
		ModLoader.addLocalization("entity.PetGhost.name", "ja_JP", "[ペット]ゴースト");
		ModLoader.addLocalization("entity.PetGigantesu.name", "ja_JP", "[ペット]ギガンテス");
		ModLoader.addLocalization("entity.PetGoremu.name", "ja_JP", "[ペット]ゴーレム");
		ModLoader.addLocalization("entity.PetHagumeta.name", "ja_JP", "[ペット]はぐれメタル");
		ModLoader.addLocalization("entity.PetHitokuibako.name", "ja_JP", "[ペット]ひとくいばこ");
		ModLoader.addLocalization("entity.PetIkkakuusagi.name", "ja_JP", "[ペット]いっかくうさぎ");
		ModLoader.addLocalization("entity.PetKimera.name", "ja_JP", "[ペット]キメラ");
		ModLoader.addLocalization("entity.PetKingsura.name", "ja_JP", "[ペット]キングスライム");
		ModLoader.addLocalization("entity.PetKiramasin.name", "ja_JP", "[ペット]キラーマシン");
		ModLoader.addLocalization("entity.PetKirapan.name", "ja_JP", "[ペット]キラーパンサー");
		ModLoader.addLocalization("entity.PetKirikabuobake.name", "ja_JP", "[ペット]きりかぶおばけ");
		ModLoader.addLocalization("entity.PetKuinsuraimu.name", "ja_JP", "[ペット]クイーンスライム");
		ModLoader.addLocalization("entity.PetLittleEsterk.name", "ja_JP", "[ペット]リトルエスターク");
		ModLoader.addLocalization("entity.PetMetoroghost.name", "ja_JP", "[ペット]メトロゴースト");
		ModLoader.addLocalization("entity.PetSura.name", "ja_JP", "[ペット]スライム");
		ModLoader.addLocalization("entity.PetSuraimunaito.name", "ja_JP", "[ペット]スライムナイト");
		ModLoader.addLocalization("entity.PetSuraimutawa.name", "ja_JP", "[ペット]スライムタワー");
		ModLoader.addLocalization("entity.PetSyado.name", "ja_JP", "[ペット]シャドー");






	}

}