package net.minecraft.src.dqmcore;
import net.minecraft.src.*;

public class DqmAddName extends mod_Dqm
{

	public DqmAddName()
	{}
	public static void setName()
	{
		//アイテム名************************************************************************************************************************
		ModLoader.addName(Redoubu, "ja_JP", "レッドオーブ");
		ModLoader.addName(Redoubu, "Red of Orb");
		ModLoader.addName(Amatuyunoito, "ja_JP", "あまつゆの糸");
		ModLoader.addName(Amatuyunoito, "Yarn of Amatsuyu");
		ModLoader.addName(Bakudanisi, "ja_JP", "爆弾石");
		ModLoader.addName(Bakudanisi, "Stone Bomb");
		ModLoader.addName(Bannouyaku, "ja_JP", "万能薬");
		ModLoader.addName(Bannouyaku, "Panacea");
		ModLoader.addName(Doragonkira, "Dragon Killer");
		ModLoader.addName(Doragonkira, "ja_JP", "ドラゴンキラー");
		ModLoader.addName(Ginganoturugi, "ja_JP", "銀河の剣");
		ModLoader.addName(Ginganoturugi,"Sword of Galaxy");
		ModLoader.addName(Goldburesuretto, "Gold Bracelet");
		ModLoader.addName(Goldburesuretto, "ja_JP", "ゴールドブレスレット");
		ModLoader.addName(Goldring, "Gold Ring");
		ModLoader.addName(Goldring, "ja_JP", "ゴールドリング");
		ModLoader.addName(Haganenokabuto, "Helmet of Hagane");
		ModLoader.addName(Haganenokabuto, "ja_JP", "鋼の兜");
		ModLoader.addName(Haganenokote, "Gauntlet of Hagane");
		ModLoader.addName(Haganenokote, "ja_JP", "鋼の小手");
		ModLoader.addName(Haganenokutu, "Boots of Hagane");
		ModLoader.addName(Haganenokutu, "ja_JP", "鋼のグリーブ");
		ModLoader.addName(Haganenoturugi, "ja_JP", "鋼の剣");
		ModLoader.addName(Haganenoturugi, "Sword of steel");
		ModLoader.addName(Haganenoyoroi, "Armor of Hagane");
		ModLoader.addName(Haganenoyoroi, "ja_JP", "鋼の鎧");
		ModLoader.addName(Hayabusanoturugi, "ja_JP", "はやぶさの剣");
		ModLoader.addName(Hayabusanoturugi, "Sword of Falcon ");
		ModLoader.addName(Hayatenoring, "ja_JP", "疾風のリング");
		ModLoader.addName(Hayatenoring, "Ring of Fast");
		ModLoader.addName(Heisinoken, "ja_JP", "兵士の剣");
		ModLoader.addName(Heisinoken, "Sword of the soldier");
		ModLoader.addName(Hikarinoisi, "ja_JP", "光の石");
		ModLoader.addName(Hikarinoisi, "Stone of Light");
		ModLoader.addName(Hokoranokagi, "ja_JP", "ほこらのかぎ");
		ModLoader.addName(Hokoranokagi, "Shrine of key");
		ModLoader.addName(Honehone, "Bone Bone");
		ModLoader.addName(Honehone, "ja_JP", "ホネホネ");
		ModLoader.addName(Honoonoyoroi, "Armor of Flame");
		ModLoader.addName(Honoonoyoroi, "ja_JP", "炎の鎧");
		ModLoader.addName(Hosifuru, "ja_JP", "ほしふる腕輪");
		ModLoader.addName(Hosifuru, "Shooting Star Bracelet");
		ModLoader.addName(Hosinokakera, "ja_JP", "ほしのカケラ");
		ModLoader.addName(Hosinokakera, "Pieces of Star");
		ModLoader.addName(Ikazutinotama, "Ball of thunder");
		ModLoader.addName(Ikazutinotama, "ja_JP", "いかずちの玉");
		ModLoader.addName(Inferunosword, "ja_JP", "インフェルノソード");
		ModLoader.addName(Inferunosword, "Sword of Inferno");
		ModLoader.addName(Inferunoswordnoha, "Blade of Inferno");
		ModLoader.addName(Inferunoswordnoha, "ja_JP", "インフェルノソードの刃");
		ModLoader.addName(Inferunoswordnotuka, "Hilt of Inferno");
		ModLoader.addName(Inferunoswordnotuka, "ja_JP", "インフェルノソードの柄");
		ModLoader.addName(Inotinoisi, "ja_JP", "いのちの石");
		ModLoader.addName(Inotinoisi, "Stone of Life");
		ModLoader.addName(Jouyakusou, "ja_JP", "上やくそう");
		ModLoader.addName(Jouyakusou, "Over the medicinal plants");
		ModLoader.addName(Kagaminoisi, "ja_JP", "かがみの石");
		ModLoader.addName(Kagaminoisi, "Stone of Mirror");
		ModLoader.addName(Kawanobousi, "Cap of Leather");
		ModLoader.addName(Kawanobousi, "ja_JP", "皮のぼうし");
		ModLoader.addName(Kawanokote, "Gauntlet of Leather");
		ModLoader.addName(Kawanokote, "ja_JP", "皮のこて");
		ModLoader.addName(Kawanokutu, "ja_JP", "皮のくつ");
		ModLoader.addName(Kawanokutu, "Shoes of Leather");
		ModLoader.addName(Kawanoyoroi, "Armor of Leather");
		ModLoader.addName(Kawanoyoroi, "ja_JP", "皮の鎧");
		ModLoader.addName(Kazekirinohane, "ja_JP", "風切りの羽根");
		ModLoader.addName(Kazekirinohane, "Wings of The Wind");
		ModLoader.addName(Kazekirinoyumi, "Bow of The Wind");
		ModLoader.addName(Kazekirinoyumi, "ja_JP", "風切りの弓");
		ModLoader.addName(Kenjanoisi, "ja_JP", "けんじゃの石");
		ModLoader.addName(Kenjanoisi, "Philosopher's Stone");
		ModLoader.addName(Kimeranotubasa, "ja_JP", "キメラのつばさ");
		ModLoader.addName(Kimeranotubasa, "Wings of the chimeric");
		ModLoader.addName(Kinkai, "Gold Bullion");
		ModLoader.addName(Kinkai, "ja_JP", "金塊");
		ModLoader.addName(Kisekinoturugi, "ja_JP", "奇跡の剣");
		ModLoader.addName(Kisekinoturugi, "Sword of Miracles");
		ModLoader.addName(Koorinokessyou, "Ice Crystal");
		ModLoader.addName(Koorinokessyou, "ja_JP", "こおりの結晶");
		ModLoader.addName(Koorinoyaiba, "Blade of Ice");
		ModLoader.addName(Koorinoyaiba, "ja_JP", "氷の刃");
		ModLoader.addName(Koumorinohane, "Bat wings");
		ModLoader.addName(Koumorinohane, "ja_JP", "こうもりの羽根");
		ModLoader.addName(Kyodainakiba, "Giant Fang");
		ModLoader.addName(Kyodainakiba, "ja_JP", "巨大な牙");
		ModLoader.addName(Littlemedal, "ja_JP", "ちいさなメダル");
		ModLoader.addName(Littlemedal, "Little Medals");
		ModLoader.addName(Madarakumonoito, "ja_JP", "まだらクモ糸");
		ModLoader.addName(Madarakumonoito, "spider silk Madara");
		ModLoader.addName(Mahounokagi, "ja_JP", "まほうのかぎ");
		ModLoader.addName(Mahounokagi, "Magic of key");
		ModLoader.addName(Majuunokawa, "ja_JP", "まじゅうの皮");
		ModLoader.addName(Majuunokawa, "Skin of the Beast");
		ModLoader.addName(Majuunotuno, "Corner of the Beast");
		ModLoader.addName(Majuunotuno, "ja_JP", "まじゅうの角");
		ModLoader.addName(Mamorinotane, "ja_JP", "まもりのたね");
		ModLoader.addName(Mamorinotane, "Seed of Defense");
		ModLoader.addName(Metaloubu, "ja_JP", "メタルオーブ");
		ModLoader.addName(Metaloubu, "Metal Orb");
		ModLoader.addName(Metaru, "ja_JP", "ヘビーメタル");
		ModLoader.addName(Metaru, "Metal");
		ModLoader.addName(Metarukingnoha, "Blade of Metal");
		ModLoader.addName(Metarukingnoha, "ja_JP", "メタルキングの刃");
		ModLoader.addName(Metarukingnokabuto, "Helmet of Metal King");
		ModLoader.addName(Metarukingnokabuto, "ja_JP", "メタルキングの兜");
		ModLoader.addName(Metarukingnokote, "Gauntlet of Metal King");
		ModLoader.addName(Metarukingnokote, "ja_JP", "メタルキングの小手");
		ModLoader.addName(Metarukingnokutu, "Boots of Metal King");
		ModLoader.addName(Metarukingnokutu, "ja_JP", "メタルキングブーツ");
		ModLoader.addName(Metarukingnotuka, "Hilt of Metal");
		ModLoader.addName(Metarukingnotuka, "ja_JP", "メタルキングの柄");
		ModLoader.addName(Metarukingnoturugi, "ja_JP", "メタルキングの剣");
		ModLoader.addName(Metarukingnoturugi, "Sword of King Metal");
		ModLoader.addName(Metarukingnoyoroi, "Armor of Metal King");
		ModLoader.addName(Metarukingnoyoroi, "ja_JP", "メタルキングの鎧");
		ModLoader.addName(Midorinokoke, "ja_JP", "みどりコケ");
		ModLoader.addName(Midorinokoke, "Moss green");
		ModLoader.addName(Migakizuna, "ja_JP", "磨き砂");
		ModLoader.addName(Migakizuna, "Polishing Sand");
		ModLoader.addName(Mirayoroi, "Armor of Mirror");
		ModLoader.addName(Mirayoroi, "ja_JP", "ミラーアーマー");
		ModLoader.addName(Misriru, "ja_JP", "ミスリル");
		ModLoader.addName(Misriru, "Mithril");
		ModLoader.addName(MysteryEgg, "ja_JP", "謎の卵");
		ModLoader.addName(MysteryEgg, "Mystery Egg");
		ModLoader.addName(Oriharukon, "ja_JP", "オリハルコン");
		ModLoader.addName(Oriharukon, "Orichalcum");
		ModLoader.addName(Puratina, "ja_JP", "プラチナ");
		ModLoader.addName(Puratina, "Platinum");
		ModLoader.addName(Rengokunohane, "Feathers purgatory");
		ModLoader.addName(Rengokunohane, "ja_JP", "れんごくの羽根");
		ModLoader.addName(Rotonoha, "Blade of Roto");
		ModLoader.addName(Rotonoha, "ja_JP", "ロトの刃");
		ModLoader.addName(Rotonokabuto, "Helmet of Roto");
		ModLoader.addName(Rotonokabuto, "ja_JP", "ロトの兜");
		ModLoader.addName(Rotonokote, "Gauntlet of Roto");
		ModLoader.addName(Rotonokote, "ja_JP", "ロトの小手");
		ModLoader.addName(Rotonokutu, "Boots of Roto");
		ModLoader.addName(Rotonokutu, "ja_JP", "ロトの靴");
		ModLoader.addName(Rotonotate, "ja_JP", "ロトの盾");
		ModLoader.addName(Rotonotate, "Shield of Roto");
		ModLoader.addName(Rotonotuka, "Hilt of Roto");
		ModLoader.addName(Rotonotuka, "ja_JP", "ロトの柄");
		ModLoader.addName(Rotonoturugi, "ja_JP", "ロトの剣");
		ModLoader.addName(Rotonoturugi, "Sword of Roto");
		ModLoader.addName(Rotonoyoroi, "Armor of Roto");
		ModLoader.addName(Rotonoyoroi, "ja_JP", "ロトの鎧");
		ModLoader.addName(Ryuunonamida, "ja_JP", "竜のなみだ");
		ModLoader.addName(Ryuunonamida, "Tears of the Dragon");
		ModLoader.addName(Sabitakabuto, "Helmet of Old");
		ModLoader.addName(Sabitakabuto, "ja_JP", "錆びたロトの兜");
		ModLoader.addName(Sabitakote, "Gauntlet of Old");
		ModLoader.addName(Sabitakote, "ja_JP", "錆びたロトの小手");
		ModLoader.addName(Sabitakutu, "Boots of Old");
		ModLoader.addName(Sabitakutu, "ja_JP", "錆びたロトの靴");
		ModLoader.addName(Sabitatate, "ja_JP", "錆びたロトの盾");
		ModLoader.addName(Sabitatate, "Shield of Old");
		ModLoader.addName(Sabitayoroi, "Armor of Old");
		ModLoader.addName(Sabitayoroi, "ja_JP", "錆びたロトの鎧");
		ModLoader.addName(Saigonokagi, "ja_JP", "さいごのかぎ");
		ModLoader.addName(Saigonokagi, "Last of key");
		ModLoader.addName(Sefiramunoyumi, "Bow Sefiramu");
		ModLoader.addName(Sefiramunoyumi, "ja_JP", "セフィラムの弓");
		ModLoader.addName(Seijanohai, "Ash of the Saints");
		ModLoader.addName(Seijanohai, "ja_JP", "聖者の灰");
		ModLoader.addName(Seireiseki, "Elemental Stone");
		ModLoader.addName(Seireiseki, "ja_JP", "精霊石");
		ModLoader.addName(Sekaijunoha, "ja_JP", "せかいじゅの葉");
		ModLoader.addName(Sekaijunoha, "Leaves of the World Tree");
		ModLoader.addName(Sinkanohiseki, "ja_JP", "進化の秘石");
		ModLoader.addName(Sinkanohiseki, "Secret stone of evolution");
		ModLoader.addName(Sinpinoyoroi, "Armor of Mystery");
		ModLoader.addName(Sinpinoyoroi, "ja_JP", "神秘の鎧");
		ModLoader.addName(Subayasanotane, "ja_JP", "すばやさのたね");
		ModLoader.addName(Subayasanotane, "Seed of Quick");
		ModLoader.addName(Suraimuhead, "ja_JP", "スライムヘッド");
		ModLoader.addName(Suraimuhead, "Slime Head");
		ModLoader.addName(Suraimunokanmuri, "Crown of slime");
		ModLoader.addName(Suraimunokanmuri, "ja_JP", "スライムの冠");
		ModLoader.addName(Suraimuzeri, "ja_JP", "スライムゼリー");
		ModLoader.addName(Suraimuzeri, "Slime jelly");
		ModLoader.addName(Kenjanoseisui, "Philosopher's of holy water");
		ModLoader.addName(Kenjanoseisui, "ja_JP", "賢者の聖水");
		ModLoader.addName(Taiyounoisi, "ja_JP", "たいようの石");
		ModLoader.addName(Taiyounoisi, "Stone of Sun");
		ModLoader.addName(Tekkouseki, "ja_JP", "鉄鋼石");
		ModLoader.addName(Tekkouseki, "Steel stone");
		ModLoader.addName(Tikaranotane, "ja_JP", "ちからのたね");
		ModLoader.addName(Tikaranotane, "Seed of Power");
		ModLoader.addName(Togetogenokiba, "Fang spine");
		ModLoader.addName(Togetogenokiba, "ja_JP", "トゲトゲの牙");
		ModLoader.addName(Tokinosuisyou, "ja_JP", "時の水晶");
		ModLoader.addName(Tokinosuisyou, "Time of crystal");
		ModLoader.addName(Tokuyakusou, "ja_JP", "特やくそう");
		ModLoader.addName(Tokuyakusou, "Over the Special medicinal plants");
		ModLoader.addName(Toraidento, "ja_JP", "トライデント");
		ModLoader.addName(Toraidento, "Trident");
		ModLoader.addName(Touzokunokagi, "ja_JP", "とうぞくのかぎ");
		ModLoader.addName(Touzokunokagi, "Thief of key");
		ModLoader.addName(Tyounohane, "Butterfly wings");
		ModLoader.addName(Tyounohane, "ja_JP", "ちょうの羽");
		ModLoader.addName(Uminarinotue, "ja_JP", "海鳴りの杖");
		ModLoader.addName(Uminarinotue, "The sea noise wand");
		ModLoader.addName(Urokonoyoroi, "Armor of Scale");
		ModLoader.addName(Urokonoyoroi, "ja_JP", "うろこの鎧");
		ModLoader.addName(Uruwasikinoko, "Beauty or let mushroom");
		ModLoader.addName(Uruwasikinoko, "ja_JP", "うるわしキノコ");
		ModLoader.addName(Usaginosippo, "ja_JP", "うさぎのしっぽ");
		ModLoader.addName(Usaginosippo, "Tail of the rabbit");
		ModLoader.addName(Yaibanoyoroi, "Armor of the Blade");
		ModLoader.addName(Yaibanoyoroi, "ja_JP", "刃の鎧");
		ModLoader.addName(Yakusou, "ja_JP", "やくそう");
		ModLoader.addName(Yakusou, "Medicinal Herb");
		ModLoader.addName(Yawarakauru, "ja_JP", "やわらかウール");
		ModLoader.addName(Yawarakauru, "Soft wool");
		ModLoader.addName(Yogoretahoutai, "Dirty bandage");
		ModLoader.addName(Yogoretahoutai, "ja_JP", "よごれた包帯");
		ModLoader.addName(Yougansekinokakera, "Fragments of lava stone");
		ModLoader.addName(Yougansekinokakera, "ja_JP", "溶岩石のかけら");
		ModLoader.addName(Yuuwakunoyumi, "Bow of temptation");
		ModLoader.addName(Yuuwakunoyumi, "ja_JP", "ゆうわくの弓");
		ModLoader.addName(Debugsword, "Bow of Debug Sword");
		ModLoader.addName(Debugsword, "ja_JP", "デバッグソード");
		ModLoader.addName(Oujanoturugi, "Sword of King");
		ModLoader.addName(Oujanoturugi, "ja_JP", "王者のつるぎ");
		ModLoader.addName(Papasunoturugi, "Sword of Papasu");
		ModLoader.addName(Papasunoturugi, "ja_JP", "パパスのつるぎ");
		ModLoader.addName(Papasunoturuginew, "Sword of Papasu New");
		ModLoader.addName(Papasunoturuginew, "ja_JP", "パパスのつるぎ改");
		ModLoader.addName(Doragonmeiru, "Armor of Dragon");
		ModLoader.addName(Doragonmeiru, "ja_JP", "ドラゴンメイル");
		ModLoader.addName(Dokukesisou, "Antidote for poison herb");
		ModLoader.addName(Dokukesisou, "ja_JP", "どくけしそう");
		ModLoader.addName(Suraimunofuku, "Slime Clothes");
		ModLoader.addName(Suraimunofuku, "ja_JP", "スライムのふく");
		ModLoader.addName(Rakkipendanto, "Lucky pendant");
		ModLoader.addName(Rakkipendanto, "ja_JP", "ラッキーペンダント");
		ModLoader.addName(Tikaranorubi, "Ruby of force");
		ModLoader.addName(Tikaranorubi, "ja_JP", "ちからのルビー");
		ModLoader.addName(Gouketunoudewa, "Heroes bangles");
		ModLoader.addName(Gouketunoudewa, "ja_JP", "ごうけつの腕輪");
		ModLoader.addName(Mamorinorubi, "Ruby defensive");
		ModLoader.addName(Mamorinorubi, "ja_JP", "まもりのルビー");
		ModLoader.addName(Rubinogenseki, "Ruby Ore");
		ModLoader.addName(Rubinogenseki, "ja_JP", "ルビーの原石");
		ModLoader.addName(Papasunokatami, "Papas keepsake");
		ModLoader.addName(Papasunokatami, "ja_JP", "パパスの形見");
		ModLoader.addName(Ramia, "Soul of the sacred bird");
		ModLoader.addName(Ramia, "ja_JP", "霊鳥の魂");
		ModLoader.addName(Dragonwing, "Dragon Wing");
		ModLoader.addName(Dragonwing, "ja_JP", "ドラゴンウィング");
		ModLoader.addName(Hikarinotue, "Wand of light");
		ModLoader.addName(Hikarinotue, "ja_JP", "ひかりの杖");
		ModLoader.addName(Moon, "Diamond of the moon");
		ModLoader.addName(Moon, "ja_JP", "月のダイヤ");
		ModLoader.addName(Ikazutinotue, "Staff of Lightning");
		ModLoader.addName(Ikazutinotue, "ja_JP", "いかずちのつえ");
		ModLoader.addName(Ookanaduti, "Big hammer");
		ModLoader.addName(Ookanaduti, "ja_JP", "おおかなづち");
		ModLoader.addName(Atorasunokanaduti, "Atlas hammer");
		ModLoader.addName(Atorasunokanaduti, "ja_JP", "アトラスのかなづち");
		ModLoader.addName(Gureitoakusu, "Great Axe");
		ModLoader.addName(Gureitoakusu, "ja_JP", "グレートアックス");
		ModLoader.addName(Dragonrod, "Dragon rod");
		ModLoader.addName(Dragonrod, "ja_JP", "ドラゴンロッド");
		ModLoader.addName(Sabakinotue, "Wand of justice");
		ModLoader.addName(Sabakinotue, "ja_JP", "さばきのつえ");
		ModLoader.addName(Majuunotume, "Claw of beast");
		ModLoader.addName(Majuunotume, "ja_JP", "まじゅうのつめ");
		ModLoader.addName(Seinarunaifu, "Holy knife");
		ModLoader.addName(Seinarunaifu, "ja_JP", "せいなるナイフ");
		ModLoader.addName(Yaibanobumeran, "Boomerang blade");
		ModLoader.addName(Yaibanobumeran, "ja_JP", "やいばのブーメラン");
		ModLoader.addName(Majinnokanaduti, "Hammer of Demon");
		ModLoader.addName(Majinnokanaduti, "ja_JP", "まじんのかなづち");
		ModLoader.addName(Oninokanabou, "Kanabo of ogre");
		ModLoader.addName(Oninokanabou, "ja_JP", "おにのかなぼう");
		ModLoader.addName(Akumanotume, "Devil's claw");
		ModLoader.addName(Akumanotume, "ja_JP", "あくまのつめ");
		ModLoader.addName(Dokubari, "Stinger");
		ModLoader.addName(Dokubari, "ja_JP", "どくばり");
		ModLoader.addName(Buruoubu, "Blue Orb");
		ModLoader.addName(Buruoubu, "ja_JP", "ブルーオーブ");
		ModLoader.addName(Ierooubu, "Yellow Orb");
		ModLoader.addName(Ierooubu, "ja_JP", "イエローオーブ");
		ModLoader.addName(Gurinoubu, "Green Orb");
		ModLoader.addName(Gurinoubu, "ja_JP", "グリーンオーブ");
		ModLoader.addName(Paapuruoubu, "パープルオーブ");
		ModLoader.addName(Paapuruoubu, "ja_JP", "パープルオーブ");



		//モンスター名（日）************************************************************************************************************************************************************
		ModLoader.addLocalization("entity.Arumiraji.name", "ja_JP", "アルミラージ");
		ModLoader.addLocalization("entity.Atorasu.name", "ja_JP", "アトラス");
		ModLoader.addLocalization("entity.Ayasiikage.name", "ja_JP", "あやしいかげ");
		ModLoader.addLocalization("entity.Bakudaniwa.name", "ja_JP", "ばくだんいわ");
		ModLoader.addLocalization("entity.BigCrow.name", "ja_JP", "おおガラス");
		ModLoader.addLocalization("entity.Bubsura.name", "ja_JP", "バブルスライム");
		ModLoader.addLocalization("entity.Buraddihando.name", "ja_JP", "ブラッディハンド");
		ModLoader.addLocalization("entity.Desufuratta.name", "ja_JP", "デスフラッター");
		ModLoader.addLocalization("entity.Doraki.name", "ja_JP", "ドラキー");
		ModLoader.addLocalization("entity.Dorakima.name", "ja_JP", "ドラキーマ");
		ModLoader.addLocalization("entity.Dqmdragon.name", "ja_JP", "ドラゴン");
		ModLoader.addLocalization("entity.Esterk.name", "ja_JP", "エスターク");
		ModLoader.addLocalization("entity.Furosutogizumo.name", "ja_JP", "フロストギズモ");
		ModLoader.addLocalization("entity.Gaikotukensi.name", "ja_JP", "がいこつけんし");
		ModLoader.addLocalization("entity.Ghost.name", "ja_JP", "ゴースト");
		ModLoader.addLocalization("entity.Gigantesu.name", "ja_JP", "ギガンテス");
		ModLoader.addLocalization("entity.Gizumo.name", "ja_JP", "ギズモ");
		ModLoader.addLocalization("entity.Goremu.name", "ja_JP", "ゴーレム");
		ModLoader.addLocalization("entity.Hagumeta.name", "ja_JP", "はぐれメタル");
		ModLoader.addLocalization("entity.Herughost.name", "ja_JP", "ヘルゴースト");
		ModLoader.addLocalization("entity.Hiitogizumo.name", "ja_JP", "ヒートギズモ");
		ModLoader.addLocalization("entity.Hitokuibako.name", "ja_JP", "ひとくいばこ");
		ModLoader.addLocalization("entity.Hoimisura.name", "ja_JP", "ホイミスライム");
		ModLoader.addLocalization("entity.Horoghost.name", "ja_JP", "ホロゴースト");
		ModLoader.addLocalization("entity.Ikkakuusagi.name", "ja_JP", "いっかくうさぎ");
		ModLoader.addLocalization("entity.Kimera.name", "ja_JP", "キメラ");
		ModLoader.addLocalization("entity.Kingsura.name", "ja_JP", "キングスライム");
		ModLoader.addLocalization("entity.Kiramasin.name", "ja_JP", "キラーマシン");
		ModLoader.addLocalization("entity.Kirapan.name", "ja_JP", "キラーパンサー");
		ModLoader.addLocalization("entity.Kirikabuobake.name", "ja_JP", "きりかぶおばけ");
		ModLoader.addLocalization("entity.Kuinsuraimu.name", "ja_JP", "クイーンスライム");
		ModLoader.addLocalization("entity.Madohando.name", "ja_JP", "マドハンド");
		ModLoader.addLocalization("entity.Maounokage.name", "ja_JP", "まおうのかげ");
		ModLoader.addLocalization("entity.Metaking.name", "ja_JP", "メタルキング");
		ModLoader.addLocalization("entity.Metaruhanta.name", "ja_JP", "メタルハンター（弓）");
		ModLoader.addLocalization("entity.Metaruhantaken.name", "ja_JP", "メタルハンター（剣）");
		ModLoader.addLocalization("entity.Metasura.name", "ja_JP", "メタルスライム");
		ModLoader.addLocalization("entity.Metoroghost.name", "ja_JP", "メトロゴースト");
		ModLoader.addLocalization("entity.Mimikku.name", "ja_JP", "ミミック");
		ModLoader.addLocalization("entity.Pandorabox.name", "ja_JP", "パンドラボックス");
		ModLoader.addLocalization("entity.Riripat.name", "ja_JP", "リリパット");
		ModLoader.addLocalization("entity.Sura.name", "ja_JP", "スライム");
		ModLoader.addLocalization("entity.Suraimubehomazun.name", "ja_JP", "スライムベホマズン");
		ModLoader.addLocalization("entity.Suraimubesu.name", "ja_JP", "スライムベス");
		ModLoader.addLocalization("entity.Suraimutawa.name", "ja_JP", "スライムタワー");
		ModLoader.addLocalization("entity.Syado.name", "ja_JP", "シャドー");
		ModLoader.addLocalization("entity.Tahodoraki.name", "ja_JP", "タホドラキー");
		ModLoader.addLocalization("entity.Waraibukuro.name", "ja_JP", "わらいぶくろ");
		ModLoader.addLocalization("entity.Zinmentyo.name", "ja_JP", "じんめんちょう");
		ModLoader.addLocalization("entity.Zoma.name", "ja_JP", "ゾーマ");
		ModLoader.addLocalization("entity.Suraimunaito.name", "ja_JP", "スライムナイト");
		ModLoader.addLocalization("entity.Metaruraida.name", "ja_JP", "メタルライダー");

		ModLoader.addLocalization("entity.Behoimisuraimu.name", "ja_JP", "ベホイミスライム");
		ModLoader.addLocalization("entity.Behoimusuraimu.name", "ja_JP", "ベホイムスライム");
		ModLoader.addLocalization("entity.Dasudragon.name", "ja_JP", "ダースドラゴン");
		ModLoader.addLocalization("entity.Gamegon.name", "ja_JP", "ガメゴン");
		ModLoader.addLocalization("entity.Gamegonload.name", "ja_JP", "ガメゴンロード");
		ModLoader.addLocalization("entity.Gamegonrejendo.name", "ja_JP", "ガメゴンレジェンド");
		ModLoader.addLocalization("entity.Goldman.name", "ja_JP", "ゴールドマン");
		ModLoader.addLocalization("entity.Gorudensuraimu.name", "ja_JP", "ゴールデンスライム");
		ModLoader.addLocalization("entity.Gorudentotemu.name", "ja_JP", "ゴールデントーテム");
		ModLoader.addLocalization("entity.Kagenokisi.name", "ja_JP", "かげのきし");
		ModLoader.addLocalization("entity.Kisudragon.name", "ja_JP", "キースドラゴン");
		ModLoader.addLocalization("entity.Megazarurokku.name", "ja_JP", "メガザルロック");
		ModLoader.addLocalization("entity.Meijikimera.name", "ja_JP", "メイジキメラ");
		ModLoader.addLocalization("entity.Meragosuto.name", "ja_JP", "メラゴースト");
		ModLoader.addLocalization("entity.Metaruburazazu.name", "ja_JP", "メタルブラザーズ");
		ModLoader.addLocalization("entity.Puratinaking.name", "ja_JP", "プラチナキング");
		ModLoader.addLocalization("entity.Samayoutamasii.name", "ja_JP", "さまようたましい");
		ModLoader.addLocalization("entity.Sibirekurage.name", "ja_JP", "しびれくらげ");
		ModLoader.addLocalization("entity.Siryounokisi.name", "ja_JP", "しりょうのきし");
		ModLoader.addLocalization("entity.Starkimera.name", "ja_JP", "スターキメラ");
		ModLoader.addLocalization("entity.Stonman.name", "ja_JP", "ストーンマン");
		ModLoader.addLocalization("entity.Sumairurokku.name", "ja_JP", "スマイルロック");
		ModLoader.addLocalization("entity.Suraimumadyura.name", "ja_JP", "スライムマデュラ");




		ModLoader.addLocalization("entity.PetBakudaniwa.name", "ja_JP", "[ペット]ばくだんいわ");
		ModLoader.addLocalization("entity.PetDorakima.name", "ja_JP", "[ペット]ドラキーマ");
		ModLoader.addLocalization("entity.PetDqmdragon.name", "ja_JP", "[ペット]ドラゴン");
		ModLoader.addLocalization("entity.PetGaikotukensi.name", "ja_JP", "[ペット]がいこつけんし");
		ModLoader.addLocalization("entity.PetGhost.name", "ja_JP", "[ペット]ゴースト");
		ModLoader.addLocalization("entity.PetGigantesu.name", "ja_JP", "[ペット]ギガンテス");
		ModLoader.addLocalization("entity.PetGoremu.name", "ja_JP", "[ペット]ゴーレム");
		ModLoader.addLocalization("entity.PetHagumeta.name", "ja_JP", "[ペット]はぐれメタル");
		ModLoader.addLocalization("entity.PetHitokuibako.name", "ja_JP", "[ペット]ひとくいばこ");
		ModLoader.addLocalization("entity.PetIkkakuusagi.name", "ja_JP", "[ペット]いっかくうさぎ");
		ModLoader.addLocalization("entity.PetKimera.name", "ja_JP", "[ペット]キメラ");
		ModLoader.addLocalization("entity.PetKingsura.name", "ja_JP", "[ペット]キングスライム");
		ModLoader.addLocalization("entity.PetKiramasin.name", "ja_JP", "[ペット]キラーマシン");
		ModLoader.addLocalization("entity.PetKirapan.name", "ja_JP", "[ペット]キラーパンサー");
		ModLoader.addLocalization("entity.PetKirikabuobake.name", "ja_JP", "[ペット]きりかぶおばけ");
		ModLoader.addLocalization("entity.PetKuinsuraimu.name", "ja_JP", "[ペット]クイーンスライム");
		ModLoader.addLocalization("entity.PetLittleEsterk.name", "ja_JP", "[ペット]リトルエスターク");
		ModLoader.addLocalization("entity.PetMetoroghost.name", "ja_JP", "[ペット]メトロゴースト");
		ModLoader.addLocalization("entity.PetSura.name", "ja_JP", "[ペット]スライム");
		ModLoader.addLocalization("entity.PetSuraimutawa.name", "ja_JP", "[ペット]スライムタワー");
		ModLoader.addLocalization("entity.PetSyado.name", "ja_JP", "[ペット]シャドー");
		ModLoader.addLocalization("entity.PetSuraimunaito.name", "ja_JP", "[ペット]スライムナイト");
	}

}